version: '3.9'
services:
  quml2xform:
    container_name: quml2xform
    image: samagragovernance/quml2xform:latest
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    volumes:
      - gen:/app/gen
    restart: always

volumes:
  gen: